version: "3"
services:
    web:
        image: ewin/repository:todo-apii
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "1000:3000"
        networks:
            - webnet
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webnet
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - /home/docker/mongodata/db:/data/db
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webnet
networks:
    webnet: